#!/bin/bash

pid=$(netstat -anpe | grep 31338 | grep python3 | sed 's:.* \([0-9][0-9]*\)[/]python3:\1:')
if [ -z "$pid" ]; then
    echo "The feedback server does not appear to be running."
else
    echo "Attempting to halt feedback server"
    kill $pid
fi

# Check
pid=$(netstat -anpe | grep 31338 | grep python3 | sed 's:.* \([0-9][0-9]*\)[/]python3:\1:')
if [ -z "$pid" ]; then
    echo "Feedback server halt attempt succeeded."
else
    echo "Feedback server halt attempt failed."
fi
