#!/bin/bash

pid=$(netstat -anpe | grep 31339 | grep python3 | sed 's:.* \([0-9][0-9]*\)[/]python3:\1:')
if [ -z "$pid" ]; then
	echo "The data server does not appear to be running."
else
	echo "Attempting to halt data server"
	kill $pid
fi

# Check
pid=$(netstat -anpe | grep 31339 | grep python3 | sed 's:.* \([0-9][0-9]*\)[/]python3:\1:')
if [ -z "$pid" ]; then
	echo "Data server halt attempt succeeded."
else
	echo "Data server halt attempt failed."
fi
