#!/bin/bash

pid=$(ps -a | grep -i python | grep Libra | sed 's/^\([0-9][0-9]*\)[^0-9].*$/\1/')
if [ -z "$pid" ]; then
	echo "The data server does not appear to be running."
else
	echo "Attempting to halt data server"
	kill $pid
fi

# Check
pid=$(ps -a | grep -i python | grep Libra | sed 's/^\([0-9][0-9]*\)[^0-9].*$/\1/')
if [ -z "$pid" ]; then
	echo "Data server halt attempt succeeded."
else
	echo "Data server halt attempt failed."
fi
