#!/bin/bash

cd /home/samplereports/Reports-Interactive/Presentations/2nd-Presentation/

echo
echo 'Reports attempting to halt.'


#### Stop data server
#echo
#echo 'Attempting to halt data server'
#pid=$(cat data-server-pid)
#kill $pid
#
#### Verify stopped
#echo 
#echo 'Data server current state: (unpopulated if halt succeeded)'
#ps | grep $pid
#
#### Stop web server
#echo
#echo 'Attempting to halt web server'
#pid=$(cat web-server-pid)
#kill $pid
#
#### Verify stopped
#echo
#echo 'Web server current state: (unpopulated if halt succeeded, but also unpopulated when shutting down. Re-run in a few moments to verify.)'
#ps | grep $pid
#
#### Stop feedback server
#echo
#echo 'Attempting to halt feedback server'
#pid=$(cat feedback-server-pid)
#kill $pid
#
#### Verify stopped
#echo 'Feedback server current state: (unpopulated if halt succeeded, but also unpopulated when shutting down. Re-run in a few moments to verify.)'
#ps | grep $pid
#echo
#
#### Remove previous PID files
#rm data-server-pid
#rm web-server-pid
#rm feedback-server-pid
#
#### Report exit
#echo 'Reports shutdown script exiting'


### Notes
# This looks like it gets them all
ps aux | egrep 'start-|stop|Reports|feedback' | egrep -v '\|' | awk '{print $2}' | xargs kill
